apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  env.js: |
    window.__ENV__ = {
      KEYCLOAK_URL: "https://auth.cineops.local",
      KEYCLOAK_REALM: "cineops",
      KEYCLOAK_CLIENT: "frontend-client"
    };